FROM python:3.10
WORKDIR /app

COPY api/api.py api/bt.py api/main.py api/player.py api/.flaskenv api/requirements.txt ./
RUN ls
RUN pip install -r requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]
